### ISSUE TITLE
Exception saving preferences in p2 tasks

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-equinox/equinox.bundles#48]
While executing p2 tasks from command line we see on 4.24 M3 following errors reported:
```
!ENTRY org.eclipse.equinox.preferences 4 4 2022-06-01 08:42:59.310
!MESSAGE Exception saving preferences to: /workspaces/socbm775/sandreev/ws-r7.6-ewc425/opt/93000/src/segments/eclipse/eclipseRE/p2/org.eclipse.equinox.p2.engine/profileRegistry/SDKProfile.profile/.data/.settings/org.eclipse.equinox.p2.artifact.repository.prefs.
!STACK 0
java.nio.file.NoSuchFileException: /workspaces/socbm775/sandreev/ws-r7.6-ewc425/opt/93000/src/segments/eclipse/eclipseRE/p2/org.eclipse.equinox.p2.engine/profileRegistry/SDKProfile.profile/.data/.settings/org.eclipse.equinox.p2.artifact.repository.prefs
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:468)
        at java.base/sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:267)
        at java.base/java.nio.file.Files.move(Files.java:1422)
        at org.eclipse.core.internal.preferences.EclipsePreferences.write(EclipsePreferences.java:289)
        at org.eclipse.core.internal.preferences.EclipsePreferences.save(EclipsePreferences.java:1066)
        at org.eclipse.equinox.internal.p2.engine.ProfilePreferences.doSave(ProfilePreferences.java:141)
        at org.eclipse.equinox.internal.p2.engine.ProfilePreferences$SaveJob.run(ProfilePreferences.java:54)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

Most likely regression from https://github.com/eclipse-equinox/equinox.bundles/pull/8

**Comment by tjwatson** [comment]
@HannesWell can you take a look?

It is not obvious why it is complaining about the destination file `preferenceFile` not existing when the code just checked that it existed before the move call:

```java
			if (Files.exists(preferenceFile)) {
				// Write new file content to a temporary file first to not loose the old content
				// in case of a failure. If everything goes OK, it is moved to the right place.
				Path tmp = preferenceFile.resolveSibling(preferenceFile.getFileName() + BACKUP_FILE_EXTENSION);
				Files.writeString(tmp, fileContent, StandardCharsets.UTF_8);
				Files.move(tmp, preferenceFile, StandardCopyOption.REPLACE_EXISTING);
			} else {
				Files.writeString(preferenceFile, fileContent, StandardCharsets.UTF_8);
			}
```

**Comment by merks** [comment]
The error is really weird.  It complains about the **target** file not existing, but it's not required to exist is it?  The tmp file would have suffix .bak  and that's not what it's complaining about.    Perhaps some other thread is deleting the whole profile directory in parallel?

**Comment by laeubi** [comment]
> It is not obvious why it is complaining about the destination file `preferenceFile` not existing when the code just checked that it existed before the move call:

Even though between the check and the move the file could have been deleted I'm more surprised something else [according to the javadoc](https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/nio/file/Files.html#move(java.nio.file.Path,java.nio.file.Path,java.nio.file.CopyOption...)):

1. Move is supposed to fail *if the file exits* if not `StandardCopyOption.REPLACE_EXISTING` is given (what is the case here), so from the API do not see any indicateion it should ever fail if the file is **not** there
2. It is none of the "standard" exceptions the method declares for certain error conditions but a generic I/O error so maybe a os specific error condition (network share?).

**Comment by tjwatson** [comment]
> The error is really weird. It complains about the **target** file not existing, but it's not required to exist is it? The tmp file would have suffix .bak and that's not what it's complaining about. Perhaps some other thread is deleting the whole profile directory in parallel?

Right, it is confusing.  I think it could complain if the parent directory of the destination does not exist.  But the code also does a makeDirs on the parent file also.  It would seem some parallel file operations could cause this.  But that would be highly timing related. Was this a reproducible error?

**Comment by laeubi** [comment]
At laest the old code has some of `if (!sourceFile.exists())` do nothing, so don't know if the error was just hidden and/or intentionally ignored.

Also there is [Bug 468787](https://bugs.eclipse.org/bugs/show_bug.cgi?id=468787) that explicitly mentioning the behavior we see here. So from what this code claims to "not loose the old content in case of a failure", maybe one should simply catch any I/O error here and move on?

**Comment by laeubi** [comment]
By the way the error itself might be misleading at least when I take a look at `UnixCopyFile.move(UnixCopyFile.java:468) from my JDK11 the `NoSuchFileException` is thrown because of the `errno()` value **but the mentioned file in the error is always the source**.

So it more seems that the `.bak` file is already missing because it was previously moved! So to solve this, it might be better to use not a constant temp name but a counter or similar.

**Comment by laeubi** [comment]
@tjwatson you can simply add a try {} catch{IOException) that would have the same effect... maybe @iloveeclipse  can verify that this fixes the issue?

**Comment by tjwatson** [comment]
> @tjwatson you can simply add a try {} catch{IOException) that would have the same effect... maybe @iloveeclipse can verify that this fixes the issue?

At this stage (in RC2 week), my opinion is that we only have time to revert back to a known working state.  Then if others want to revisit fixing the existing NIO code then that can happen in a follow on release.

**Comment by HannesWell** [comment]
> > @tjwatson you can simply add a try {} catch{IOException) that would have the same effect... maybe @iloveeclipse can verify that this fixes the issue?
> 
> At this stage (in RC2 week), my opinion is that we only have time to revert back to a known working state. Then if others want to revisit fixing the existing NIO code then that can happen in a follow on release.

I agree that we should be really careful the moment. On the other hand the change suggested by @laeubi seems really save to me since the worst thing that can happen is that the Exception is swallowed (what is actually intended).

If you want to revert #8, you likely also have to revert #13 since it is a follow up.

But I'm not convinced that reverting #8 will solve the issue since `Files.move()` was called before as well.
It it is really the case that the bak-file was written and before the move starts or even during the move the entire directory is deleted (including the source and maybe the partially moved target file), the only way I see that the previous code prevents the propagation of the IOException is the try-catch block around `Files.move()`. So Christoph's suggestion would be equivalent.
However the logic within the catch-block makes me doubt, if it really prevents an IOException because it only returns without reattempting a full copy if only the source was deleted and not the target.

@iloveeclipse could you check if the file mentioned in the exception exists respectively the containing directory as well as the corresponding `.bak` file?

**Comment by laeubi** [comment]
I don't think the folder is really removed, this could also happen if two concurrent tasks update the same preferences.

**Comment by laeubi** [comment]
> Note: I will not make it to test with patched version today, and unlikely tomorrow, because of other tasks.

Just in case you can attach a debugger, can you create a conditional breakpoint with

`preferenceFile.getFileName().equals("org.eclipse.equinox.p2.metadata.repository.prefs")`

to see if there are different threads calling the method concurrently?

**Comment by HannesWell** [comment]
> If anything is to be done here we need a PR now and a request to the PMC to approve fixing it this late in the cycle.

I'm not sure. But what I also ask myself:
Are those exception harmful in the sense that functionality is broken or are they just annoying because they are displayed?
With the current Milestone/RC I did not noticed any problems. And from the causes we suspected here I think it could be the latter. If that is the case I would just wrap the call to Files.move() into a tray-catch block to swallow the exception as soon as the master re-opens.

**Comment by tjwatson** [comment]
Given that I cannot tell if this is a severe issue I do not think I can justify it as needing a fix and forcing a respin of RC2a.
